"""English SEO page content for Tiny Block multiplayer and voice-chat intents."""

from __future__ import annotations


PAGES = {
    "games-to-play-with-friends-on-phone": {
        "slug": "games-to-play-with-friends-on-phone",
        "title": "Games to Play With Friends on Your Phone",
        "description": "Compare mobile games to play with friends on iPhone and Android, including free multiplayer, private worlds, building, survival, and voice chat.",
        "eyebrow": "Mobile multiplayer guide",
        "lede": "Looking for something you can open on two phones and enjoy together? Compare the setup, price, world style, and voice options before choosing.",
        "answer_title": "A free building game you can start together",
        "answer": "Tiny Block is free to download on iOS and Android. Create a public world or an invite-code world, bring a friend into the same evolving 2D sandbox, and use built-in proximity voice while you mine, craft, build, and discover new biomes.",
        "media": "multiplayer",
        "media_file": "08-multiplayer.webp",
        "media_alt": "Two players exploring a Tiny Block multiplayer world on mobile",
        "media_caption": "Tiny Block multiplayer: public worlds, invite codes, and proximity voice on iOS and Android.",
        "disclaimer": True,
        "table_headers": ["Game", "Price and platforms", "Playing together", "Voice option", "Best fit"],
        "table_rows": [
            ["Tiny Block", "Free on iOS and Android", "Public worlds or private invite-code worlds", "Built-in proximity voice with a microphone on/off toggle", "Relaxed survival, building, crafting, and discovery"],
            ["Minecraft", "Paid game on mobile; Realms is an optional subscription", "Local worlds, servers, or Realms, with account and edition requirements", "Voice commonly uses a separate app or a compatible mod/add-on", "A large 3D sandbox and established servers"],
            ["Roblox", "Free on iOS and Android with optional purchases", "Join compatible experiences and parties", "Voice depends on age check, region, and experience support", "A broad catalog of community experiences"],
        ],
        "facts": [
            ["Build instead of compete", "Tiny Block is designed around a shared world. Friends can expand terrain, experiment with materials, craft tools, meet creatures, and explore rather than enter a match that resets."],
            ["Choose public or invite-only", "Browse a public world when you want to meet another player, or share an invite code when you want a private session with someone you know."],
            ["Keep talking inside the world", "Toggle the microphone on when you want to talk. Proximity voice gets quieter as players move apart, so conversation follows the exploration instead of feeling like a separate call."],
        ],
        "faqs": [
            ["What free phone game can I play with a friend?", "Tiny Block is free on iOS and Android and supports public and invite-code multiplayer worlds."],
            ["Can iPhone and Android players play together?", "Tiny Block multiplayer is available on both iOS and Android. Players join public worlds or use the same invite code."],
            ["Does Tiny Block have voice chat?", "Yes. Multiplayer includes proximity voice with a microphone on/off toggle, so nearby players sound louder and distant players fade out."],
            ["Is Tiny Block Minecraft?", "No. Tiny Block is an independent 2D survival crafting game by No Such Games and is not approved by or associated with Mojang or Microsoft."],
        ],
        "sources": [
            ["Minecraft multiplayer requirements", "https://help.minecraft.net/hc/en-us/articles/35930809028749-Requirements-to-Play-Minecraft-Multiplayer-Games"],
            ["Minecraft Realms plans and features", "https://www.minecraft.net/en-us/realms"],
            ["Roblox voice-chat requirements", "https://en.help.roblox.com/hc/en-us/articles/43611824582292-How-to-chat-on-Roblox"],
        ],
        "cluster": "friends_phone_games",
    },
    "one-block-skyblock-multiplayer": {
        "slug": "one-block-skyblock-multiplayer",
        "title": "One Block Skyblock Multiplayer",
        "description": "Learn how One Block Skyblock multiplayer works in Minecraft, then compare a free Tiny Block world with built-in public and invite-code multiplayer.",
        "eyebrow": "One Block multiplayer guide",
        "lede": "One Block is more fun when another player can help protect the tiny start, collect resources, and turn it into a living world.",
        "answer_title": "Two ways to play One Block with friends",
        "answer": "In Minecraft, multiplayer One Block usually starts with a compatible community map and a shared local world, server, or Realm. Tiny Block includes its own 2D One Block mode: install the free game, create a public or invite-code world, and grow it together without finding a separate map or hosting a Minecraft server.",
        "media": "one-block-duo",
        "media_file": "11-one-block-multiplayer.webp",
        "disclaimer": True,
        "table_headers": ["Step", "Minecraft One Block", "Tiny Block multiplayer"],
        "table_rows": [
            ["Get the game", "Buy a compatible Minecraft edition on each required device", "Download Tiny Block free on iOS or Android"],
            ["Get One Block", "Choose a Marketplace or community One Block map that supports your edition", "Start the One Block mode included in Tiny Block"],
            ["Bring a friend", "Host locally, configure a server, or create/join a Realm", "Open the world publicly or share its invite code"],
            ["Grow the island", "Use the map creator's progression and standard Minecraft crafting", "Mine, combine materials, craft, grow plants, meet creatures, and unlock generated biomes"],
            ["Talk together", "Use the platform's available communication route or a compatible voice solution", "Use built-in proximity voice and toggle the microphone on or off"],
        ],
        "facts": [
            ["Protect the tiny start", "With two players, one person can mine while the other makes safe space, moves liquids, plants trees, or keeps creatures away from the edge."],
            ["No separate map search", "Tiny Block's One Block world is a built-in mode rather than a third-party Minecraft map. Its progression is designed around Tiny Block discoveries."],
            ["A world that keeps changing", "New structures and biomes are generated from discoveries, so the shared island develops beyond the first regenerating block."],
        ],
        "faqs": [
            ["Can you play One Block Skyblock multiplayer?", "Yes. Minecraft players can use a multiplayer-compatible One Block map and shared world. Tiny Block includes a free built-in One Block mode with public and invite-code multiplayer."],
            ["Do I need a server for One Block multiplayer?", "That depends on the Minecraft edition and map. Local hosting, a server, or a Realm may be used. Tiny Block does not require you to configure a Minecraft server."],
            ["Is Tiny Block One Block free?", "Tiny Block is free to download and play on iOS and Android."],
            ["Can friends talk inside a Tiny Block world?", "Yes. Tiny Block multiplayer includes proximity voice with a microphone on/off toggle."],
        ],
        "sources": [
            ["Minecraft multiplayer requirements", "https://help.minecraft.net/hc/en-us/articles/35930809028749-Requirements-to-Play-Minecraft-Multiplayer-Games"],
            ["Official Minecraft Realms guide", "https://www.minecraft.net/en-us/realms"],
            ["Example multiplayer One Block Bedrock map", "https://www.curseforge.com/minecraft-bedrock/maps/multiplayer-one-block"],
        ],
        "cluster": "one_block_multiplayer",
    },
    "play-minecraft-with-friends-free-alternative": {
        "slug": "play-minecraft-with-friends-free-alternative",
        "title": "Play Minecraft With Friends: Free Alternative",
        "description": "See how to play Minecraft with friends, what multiplayer can require, and how Tiny Block offers a free mobile survival-building alternative.",
        "eyebrow": "Minecraft friends guide",
        "lede": "Minecraft offers several ways to play together. If cost or setup gets in the way, Tiny Block is a free independent mobile alternative built around shared worlds.",
        "answer_title": "How to play Minecraft with friends",
        "answer": "Use the same compatible Minecraft edition, sign in with the required account, enable multiplayer permissions, and then join a local world, featured server, or invited Realm. Console play may require a platform online subscription, and a Realm is an optional recurring subscription. If you want a free game you can enter together on iOS or Android, Tiny Block offers public and invite-code worlds without pretending to be Minecraft.",
        "media": "one-block-duo",
        "media_file": "08-multiplayer.webp",
        "disclaimer": True,
        "table_headers": ["Question", "Minecraft", "Tiny Block"],
        "table_rows": [
            ["Is the game free?", "Minecraft is a paid game; prices vary by platform and market", "Free to download and play on iOS and Android"],
            ["How do friends join?", "Local multiplayer, servers, invitations, or Realms; edition and account requirements apply", "Browse public worlds or enter an invite code"],
            ["Is an always-online private world included?", "Realms provides hosted private worlds through a recurring subscription", "Invite-code sessions are created inside the free game"],
            ["Is One Block built in?", "Usually provided by a community or Marketplace map", "Yes, as a purpose-built 2D game mode"],
            ["Is proximity voice built in?", "Usually handled through a compatible mod/add-on or separate communication tool", "Yes, with a microphone on/off toggle and distance-based volume"],
        ],
        "facts": [
            ["Choose Minecraft when…", "You want its full 3D sandbox, established servers, Marketplace ecosystem, and your group already owns compatible editions."],
            ["Choose Tiny Block when…", "You want a free mobile world you can start quickly, build together, and explore with voice chat already connected to player distance."],
            ["Different games, familiar goal", "Both can turn a small beginning into a shared building adventure. Tiny Block uses its own 2D simulation, discoveries, creatures, and procedural biomes."],
        ],
        "faqs": [
            ["Do you have to pay to play Minecraft with friends?", "Minecraft itself is paid. Some multiplayer routes are included, while Realms and console online services can add subscriptions depending on platform."],
            ["Can I play a free game like Minecraft with friends on mobile?", "Tiny Block is a free independent 2D survival crafting game for iOS and Android with public and invite-code multiplayer worlds."],
            ["Do all friends need the same Minecraft edition?", "Minecraft multiplayer requires compatible editions and versions. Official Minecraft support documents the current requirements."],
            ["Is Tiny Block an official Minecraft game?", "No. Tiny Block is created by No Such Games and is not approved by or associated with Mojang or Microsoft."],
        ],
        "sources": [
            ["Official Minecraft multiplayer requirements", "https://help.minecraft.net/hc/en-us/articles/35930809028749-Requirements-to-Play-Minecraft-Multiplayer-Games"],
            ["Minecraft platform and multiplayer features", "https://www.minecraft.net/en-us/about-minecraft"],
            ["Minecraft Realms pricing and features", "https://www.minecraft.net/en-us/realms"],
        ],
        "cluster": "minecraft_friends_alternative",
    },
    "multiplayer-games-with-voice-chat": {
        "slug": "multiplayer-games-with-voice-chat",
        "title": "Multiplayer Games With Voice Chat",
        "description": "Compare multiplayer games with voice chat and push-to-talk controls on iOS and Android, including proximity voice, private worlds, survival, and building.",
        "eyebrow": "Voice-chat game guide",
        "lede": "Voice can turn a multiplayer session from two silent avatars into an actual shared adventure. The right option depends on the world you want and the setup you accept.",
        "answer_title": "A survival-building game with voice included",
        "answer": "Tiny Block combines a free mobile survival sandbox with built-in proximity voice. Join a public world or share an invite code, toggle the microphone on when you want to talk, and explore: nearby players sound clear, and voices fade as distance grows.",
        "media": "multiplayer",
        "media_file": "09-multiplayer-voice.webp",
        "media_alt": "Two Tiny Block players using multiplayer proximity voice in a shared world",
        "media_caption": "Built-in proximity voice follows the players through a shared Tiny Block world.",
        "disclaimer": True,
        "table_headers": ["Option", "Mobile access", "How voice works", "World style", "Setup trade-off"],
        "table_rows": [
            ["Tiny Block", "Free on iOS and Android", "Push-to-talk-style microphone toggle: tap once on, tap again off", "Shared survival, crafting, and building worlds", "Join public worlds or use one invite code"],
            ["Roblox experiences", "Free app on iOS and Android", "Voice requires age check and a supported experience/region", "Varies by community experience", "Eligibility and experience support must match"],
            ["Minecraft with a voice solution", "Paid Minecraft editions include mobile versions", "A separate app or compatible mod/add-on is commonly used for proximity voice", "3D sandbox, servers, local worlds, and Realms", "Edition, account, world hosting, and voice setup can differ"],
        ],
        "facts": [
            ["Proximity changes the conversation", "A friend's voice is strongest nearby and fades with distance. That makes exploring a cave or getting separated feel connected to the world."],
            ["Push to talk without holding a button", "Tiny Block uses a push-to-talk-style microphone control without requiring a long press: tap once to turn the microphone on, then tap again to turn it off. Proximity volume still follows player distance."],
            ["Public or private sessions", "Use a public world for an open multiplayer session or an invite code for a shared world with people you already know."],
        ],
        "faqs": [
            ["Which mobile game has built-in proximity voice chat?", "Tiny Block includes proximity voice with a microphone on/off toggle in its multiplayer worlds on iOS and Android."],
            ["Does Tiny Block use push to talk?", "It uses a push-to-talk-style microphone toggle: tap once to start transmitting and tap again to stop, rather than holding the button."],
            ["Can I play and talk with friends without Discord?", "Yes. Tiny Block voice is built into the multiplayer session, so a separate voice-call app is not required."],
            ["Does proximity voice work everywhere in the world?", "Voice volume follows player distance. Nearby players are clear; distant players become quieter and eventually inaudible."],
            ["Can I make the multiplayer world private?", "Yes. Create an invite-code world and share the code with the players you want to join."],
        ],
        "sources": [
            ["Roblox voice controls and eligibility", "https://en.help.roblox.com/hc/en-us/articles/43611824582292-How-to-chat-on-Roblox"],
            ["Minecraft multiplayer requirements", "https://help.minecraft.net/hc/en-us/articles/35930809028749-Requirements-to-Play-Minecraft-Multiplayer-Games"],
            ["Example Minecraft proximity voice add-on", "https://www.curseforge.com/minecraft-bedrock/addons/proximity-voice-chat-and-proximity-text-chat-2-2"],
        ],
        "cluster": "multiplayer_voice_chat",
    },
    "minecraft-proximity-chat-alternative": {
        "slug": "minecraft-proximity-chat-alternative",
        "title": "Minecraft Proximity Chat Alternative",
        "description": "Compare Minecraft proximity chat mods and add-ons with Tiny Block, a free mobile survival game where distance-based voice is built into multiplayer.",
        "eyebrow": "Proximity voice comparison",
        "lede": "Minecraft proximity chat searches usually lead to a mod, add-on, plug-in, or external voice tool. Tiny Block takes a different route by building distance-based voice into the multiplayer world.",
        "answer_title": "Want proximity chat without installing a Minecraft mod?",
        "answer": "Install Tiny Block free on iOS or Android, join a public world or enter an invite code, and use built-in proximity voice with a microphone on/off toggle. It is an independent 2D survival crafting game—not a Minecraft mod—but it answers the same desire to explore, build, and hear nearby friends without configuring a separate voice system.",
        "media": "multiplayer",
        "media_file": "09-multiplayer-voice.webp",
        "media_alt": "Two players standing together in a Tiny Block world with built-in proximity voice",
        "media_caption": "Tiny Block makes proximity voice part of the multiplayer world rather than a separate mod.",
        "disclaimer": True,
        "table_headers": ["Feature", "Minecraft proximity chat route", "Tiny Block"],
        "table_rows": [
            ["Base game", "Requires a compatible paid Minecraft edition", "Free on iOS and Android"],
            ["Voice installation", "Usually a compatible mod, add-on, plug-in, or external communication tool", "Included in the game"],
            ["Distance effect", "Depends on the selected voice solution and server/client compatibility", "Built-in volume falloff based on player distance"],
            ["World access", "Local host, server, or Realm requirements vary by edition", "Public browser or private invite code"],
            ["Gameplay", "Minecraft's 3D sandbox and the selected server/map", "Tiny Block's 2D survival, crafting, discoveries, creatures, and procedural biomes"],
        ],
        "facts": [
            ["It is not a Minecraft mod", "Tiny Block does not alter Minecraft and cannot join Minecraft servers. It is a separate game with its own worlds and systems."],
            ["Voice follows distance", "Full volume is reserved for nearby players; voices fade as players separate and stop beyond the in-game voice range."],
            ["Designed for mobile sessions", "The world browser, invite codes, touch controls, and voice control are part of the same iOS and Android experience."],
        ],
        "faqs": [
            ["Does Minecraft have built-in proximity chat?", "Minecraft proximity voice commonly relies on a compatible mod, add-on, plug-in, or separate voice tool. Availability depends on edition and setup."],
            ["What is a free alternative with proximity voice?", "Tiny Block is a free independent mobile survival-building game with proximity voice and a microphone on/off toggle built into multiplayer."],
            ["Is Tiny Block voice push to talk?", "The control follows the same intent, but it is a toggle rather than hold-to-talk: tap the microphone once to transmit and again to stop."],
            ["Can Tiny Block connect to a Minecraft server?", "No. Tiny Block has its own public and invite-code worlds and is not a Minecraft client or mod."],
            ["Is proximity chat the same as a group call?", "No. Proximity chat changes volume with in-world distance, while a normal group call usually keeps every participant at a similar level."],
        ],
        "sources": [
            ["Example Minecraft proximity voice and text add-on", "https://www.curseforge.com/minecraft-bedrock/addons/proximity-voice-chat-and-proximity-text-chat-2-2"],
            ["Minecraft multiplayer requirements", "https://help.minecraft.net/hc/en-us/articles/35930809028749-Requirements-to-Play-Minecraft-Multiplayer-Games"],
        ],
        "cluster": "minecraft_proximity_alternative",
    },
    "multiplayer-survival-game": {
        "slug": "multiplayer-survival-game",
        "title": "Free Multiplayer Survival Game",
        "description": "Play a free multiplayer survival crafting game on iOS and Android. Build a shared world, discover materials and biomes, and use proximity voice.",
        "eyebrow": "Survival, crafting, and co-op",
        "lede": "Tiny Block is a multiplayer survival-building game about turning a tiny beginning into a world that keeps producing new materials, creatures, structures, and biomes.",
        "answer_title": "Survival crafting that grows with both players",
        "answer": "Create a public or invite-code world and decide how to divide the work. One player can mine while another builds, manages water and lava, grows plants, crafts tools, explores caves, or follows a new biome. Proximity voice keeps coordination inside the game.",
        "media": "multiplayer",
        "media_file": "10-multiplayer-survival.webp",
        "media_alt": "Two players building and exploring together in Tiny Block multiplayer survival",
        "media_caption": "A shared Tiny Block world can grow from a small start into terrain, caves, structures, plants, and creature habitats.",
        "disclaimer": False,
        "table_headers": ["Multiplayer system", "How it works in Tiny Block", "Why it matters"],
        "table_rows": [
            ["Shared simulation", "Players move through the same changing terrain, materials, plants, creatures, and time of day", "Actions affect one living world rather than separate scores"],
            ["Public worlds", "Open a discoverable multiplayer session", "Useful when you want to find someone already playing"],
            ["Invite-code worlds", "Share a short code with a friend", "Keeps the session focused on the people you invited"],
            ["Proximity voice", "Push-to-talk-style microphone toggle; volume changes with in-world distance", "Coordinates exploration without leaving the game"],
            ["Procedural discovery", "Combinations lead to materials, items, plants, creatures, structures, and biomes", "A co-op world can continue producing new goals"],
        ],
        "facts": [
            ["Mine and build together", "Split early survival tasks or work on the same structure. Shared materials and terrain make every action visible to the other player."],
            ["Explore day, night, and caves", "Light, darkness, water, lava, habitats, and player actions change what the world reveals and how creatures behave."],
            ["More than a fixed recipe list", "The documented recipes are starting discoveries. New combinations can expand the world with additional results and generated content."],
        ],
        "faqs": [
            ["Is Tiny Block a free multiplayer survival game?", "Yes. Tiny Block is free on iOS and Android and includes public and invite-code multiplayer worlds."],
            ["Can two players build the same world?", "Yes. Multiplayer players share the world state, terrain, materials, creatures, and discoveries."],
            ["Is Tiny Block co-op or competitive?", "The core multiplayer experience is cooperative sandbox survival and building rather than a round-based competitive match."],
            ["Does multiplayer include voice chat?", "Yes. Tiny Block includes proximity voice with a microphone on/off toggle and distance-based volume."],
        ],
        "sources": [],
        "cluster": "multiplayer_survival",
    },
}
