"""Human-reviewed Tiny Block wiki UI copy and terms absent from the game catalog."""

TEXT = {
    "en": {"play":"Play free","language":"Choose language","wiki":"Wiki","biomes":"Biomes","materials":"Materials","creatures":"Creatures","plants":"Plants","recipes":"Recipes","official":"Official game guide","overview":"Explore the biomes, materials, recipes, plants, and creatures already living inside Tiny Block.","guide":"Guide","catalog":"Explore the shared starting discoveries—then create your own.","world":"World generation","biomes_intro":"Floating Islands can lead from bright plains to glaciers, beaches, caverns, and volcanic ground.","biome":"Biome","terrain":"Terrain","mining":"Mining and building","materials_intro":"Materials flow, fall, freeze, burn, and transform when they meet.","material":"Material","living":"Living worlds","creatures_intro":"Meet creatures with different behavior across daylight, water, caves, and lava.","creature":"Creature","growing":"Growing discoveries","plants_intro":"Discover flowers, vines, decorative plants, and biome-specific trees.","plant":"Plant","crafting":"Crafting","recipes_intro":"Combine discoveries to unlock tools, storage, building blocks, and light.","ingredients":"Ingredients","result":"Result","recipe_caption":"The in-game recipe catalog shows what can be made from discoveries in the current world.","game":"Game","creators":"Creators","privacy":"Privacy","infinite_kicker":"Beyond the core catalog","infinite_title":"Your discoveries do not end here","infinite_copy":"These entries are shared starting discoveries, not a complete list. Combine what you find in the game to create new materials, items, plants, and creatures—the space of possible combinations keeps growing."},
    "de": {"play":"Kostenlos spielen","language":"Sprache wählen","wiki":"Wiki","biomes":"Biome","materials":"Materialien","creatures":"Kreaturen","plants":"Pflanzen","recipes":"Rezepte","official":"Offizieller Spielguide","overview":"Entdecke die Biome, Materialien, Rezepte, Pflanzen und Kreaturen von Tiny Block.","guide":"Guide","catalog":"Entdecke gemeinsame Startfunde – und erschaffe dann deine eigenen.","world":"Weltgenerierung","biomes_intro":"Schwebende Inseln führen von hellen Ebenen zu Gletschern, Stränden, Höhlen und Vulkangestein.","biome":"Biom","terrain":"Terrain","mining":"Abbau und Bauen","materials_intro":"Materialien fließen, fallen, gefrieren, brennen und verwandeln sich.","material":"Material","living":"Lebendige Welten","creatures_intro":"Lerne Kreaturen mit unterschiedlichem Verhalten bei Licht, im Wasser, in Höhlen und Lava kennen.","creature":"Kreatur","growing":"Wachsende Entdeckungen","plants_intro":"Entdecke Blumen, Ranken, Zierpflanzen und biomspezifische Bäume.","plant":"Pflanze","crafting":"Herstellung","recipes_intro":"Kombiniere Entdeckungen zu Werkzeugen, Lagern, Baublöcken und Licht.","ingredients":"Zutaten","result":"Ergebnis","recipe_caption":"Der Rezeptkatalog zeigt, was sich aus den Entdeckungen der aktuellen Welt herstellen lässt.","game":"Spiel","creators":"Creators","privacy":"Datenschutz","infinite_kicker":"Über den Grundkatalog hinaus","infinite_title":"Deine Entdeckungen enden hier nicht","infinite_copy":"Diese Einträge sind gemeinsame Startentdeckungen, keine vollständige Liste. Kombiniere deine Funde im Spiel zu neuen Materialien, Gegenständen, Pflanzen und Kreaturen – der Raum möglicher Kombinationen wächst weiter."},
    "es": {"play":"Jugar gratis","language":"Elegir idioma","wiki":"Wiki","biomes":"Biomas","materials":"Materiales","creatures":"Criaturas","plants":"Plantas","recipes":"Recetas","official":"Guía oficial del juego","overview":"Explora los biomas, materiales, recetas, plantas y criaturas de Tiny Block.","guide":"Guía","catalog":"Explora los descubrimientos iniciales y después crea los tuyos.","world":"Generación del mundo","biomes_intro":"Las islas flotantes llevan de llanuras luminosas a glaciares, playas, cavernas y terreno volcánico.","biome":"Bioma","terrain":"Terreno","mining":"Minería y construcción","materials_intro":"Los materiales fluyen, caen, se congelan, arden y se transforman al encontrarse.","material":"Material","living":"Mundos vivos","creatures_intro":"Conoce criaturas que se comportan de forma distinta con luz, agua, cuevas y lava.","creature":"Criatura","growing":"Descubrimientos vivos","plants_intro":"Descubre flores, enredaderas, plantas decorativas y árboles de cada bioma.","plant":"Planta","crafting":"Fabricación","recipes_intro":"Combina descubrimientos para crear herramientas, almacenamiento, bloques y luz.","ingredients":"Ingredientes","result":"Resultado","recipe_caption":"El catálogo de recetas muestra qué puedes fabricar con los descubrimientos del mundo actual.","game":"Juego","creators":"Creadores","privacy":"Privacidad","infinite_kicker":"Más allá del catálogo básico","infinite_title":"Tus descubrimientos no terminan aquí","infinite_copy":"Estas entradas son descubrimientos iniciales compartidos, no una lista completa. Combina lo que encuentres para crear nuevos materiales, objetos, plantas y criaturas: el espacio de combinaciones posibles sigue creciendo."},
    "fr": {"play":"Jouer gratuitement","language":"Choisir la langue","wiki":"Wiki","biomes":"Biomes","materials":"Matériaux","creatures":"Créatures","plants":"Plantes","recipes":"Recettes","official":"Guide officiel du jeu","overview":"Explorez les biomes, matériaux, recettes, plantes et créatures de Tiny Block.","guide":"Guide","catalog":"Explorez les découvertes de départ, puis créez les vôtres.","world":"Génération du monde","biomes_intro":"Les îles flottantes mènent des plaines lumineuses aux glaciers, plages, cavernes et terres volcaniques.","biome":"Biome","terrain":"Terrain","mining":"Minage et construction","materials_intro":"Les matériaux coulent, tombent, gèlent, brûlent et se transforment au contact.","material":"Matériau","living":"Mondes vivants","creatures_intro":"Rencontrez des créatures au comportement différent selon la lumière, l’eau, les grottes et la lave.","creature":"Créature","growing":"Découvertes vivantes","plants_intro":"Découvrez fleurs, lianes, plantes décoratives et arbres propres aux biomes.","plant":"Plante","crafting":"Fabrication","recipes_intro":"Combinez vos découvertes pour créer outils, rangements, blocs et éclairage.","ingredients":"Ingrédients","result":"Résultat","recipe_caption":"Le catalogue de recettes indique ce qui peut être fabriqué avec les découvertes du monde actuel.","game":"Jeu","creators":"Créateurs","privacy":"Confidentialité","infinite_kicker":"Au-delà du catalogue de base","infinite_title":"Vos découvertes ne s’arrêtent pas ici","infinite_copy":"Ces entrées sont des découvertes de départ communes, pas une liste complète. Combinez vos trouvailles pour créer de nouveaux matériaux, objets, plantes et créatures : l’espace des combinaisons possibles continue de grandir."},
    "it": {"play":"Gioca gratis","language":"Scegli la lingua","wiki":"Wiki","biomes":"Biomi","materials":"Materiali","creatures":"Creature","plants":"Piante","recipes":"Ricette","official":"Guida ufficiale del gioco","overview":"Esplora biomi, materiali, ricette, piante e creature di Tiny Block.","guide":"Guida","catalog":"Esplora le scoperte iniziali, poi crea le tue.","world":"Generazione del mondo","biomes_intro":"Le isole fluttuanti conducono da pianure luminose a ghiacciai, spiagge, caverne e terreno vulcanico.","biome":"Bioma","terrain":"Terreno","mining":"Estrazione e costruzione","materials_intro":"I materiali scorrono, cadono, gelano, bruciano e si trasformano quando si incontrano.","material":"Materiale","living":"Mondi viventi","creatures_intro":"Incontra creature che si comportano diversamente con luce, acqua, grotte e lava.","creature":"Creatura","growing":"Scoperte in crescita","plants_intro":"Scopri fiori, rampicanti, piante decorative e alberi tipici dei biomi.","plant":"Pianta","crafting":"Creazione","recipes_intro":"Combina le scoperte per ottenere strumenti, depositi, blocchi e luce.","ingredients":"Ingredienti","result":"Risultato","recipe_caption":"Il catalogo delle ricette mostra cosa si può creare con le scoperte del mondo attuale.","game":"Gioco","creators":"Creator","privacy":"Privacy","infinite_kicker":"Oltre il catalogo di base","infinite_title":"Le tue scoperte non finiscono qui","infinite_copy":"Queste voci sono scoperte iniziali condivise, non un elenco completo. Combina ciò che trovi per creare nuovi materiali, oggetti, piante e creature: lo spazio delle combinazioni possibili continua a crescere."},
    "pt-br": {"play":"Jogar grátis","language":"Escolher idioma","wiki":"Wiki","biomes":"Biomas","materials":"Materiais","creatures":"Criaturas","plants":"Plantas","recipes":"Receitas","official":"Guia oficial do jogo","overview":"Explore os biomas, materiais, receitas, plantas e criaturas de Tiny Block.","guide":"Guia","catalog":"Explore as descobertas iniciais e depois crie as suas.","world":"Geração do mundo","biomes_intro":"Ilhas flutuantes levam de planícies claras a geleiras, praias, cavernas e terreno vulcânico.","biome":"Bioma","terrain":"Terreno","mining":"Mineração e construção","materials_intro":"Materiais fluem, caem, congelam, queimam e se transformam quando se encontram.","material":"Material","living":"Mundos vivos","creatures_intro":"Conheça criaturas com comportamentos diferentes na luz, água, cavernas e lava.","creature":"Criatura","growing":"Descobertas vivas","plants_intro":"Descubra flores, trepadeiras, plantas decorativas e árvores de cada bioma.","plant":"Planta","crafting":"Criação","recipes_intro":"Combine descobertas para criar ferramentas, armazenamento, blocos e luz.","ingredients":"Ingredientes","result":"Resultado","recipe_caption":"O catálogo de receitas mostra o que pode ser criado com as descobertas do mundo atual.","game":"Jogo","creators":"Criadores","privacy":"Privacidade","infinite_kicker":"Além do catálogo básico","infinite_title":"Suas descobertas não terminam aqui","infinite_copy":"Estas entradas são descobertas iniciais compartilhadas, não uma lista completa. Combine o que encontrar para criar novos materiais, itens, plantas e criaturas: o espaço de combinações possíveis continua crescendo."},
    "ar": {"play":"العب مجانًا","language":"اختر اللغة","wiki":"الموسوعة","biomes":"المناطق الحيوية","materials":"المواد","creatures":"المخلوقات","plants":"النباتات","recipes":"الوصفات","official":"دليل اللعبة الرسمي","overview":"استكشف المناطق الحيوية والمواد والوصفات والنباتات والمخلوقات في Tiny Block.","guide":"دليل","catalog":"استكشف اكتشافات البداية المشتركة، ثم أنشئ اكتشافاتك.","world":"توليد العالم","biomes_intro":"تقود الجزر العائمة من السهول المضيئة إلى الأنهار الجليدية والشواطئ والكهوف والأرض البركانية.","biome":"منطقة حيوية","terrain":"التضاريس","mining":"التعدين والبناء","materials_intro":"تتدفق المواد وتسقط وتتجمد وتحترق وتتحول عندما تلتقي.","material":"مادة","living":"عوالم حية","creatures_intro":"تعرّف على مخلوقات تتصرف بطرق مختلفة في الضوء والماء والكهوف والحمم.","creature":"مخلوق","growing":"اكتشافات نامية","plants_intro":"اكتشف الزهور والكروم ونباتات الزينة وأشجار المناطق الحيوية.","plant":"نبات","crafting":"التصنيع","recipes_intro":"ادمج الاكتشافات لصنع الأدوات والتخزين وكتل البناء والإضاءة.","ingredients":"المكونات","result":"النتيجة","recipe_caption":"يعرض دليل الوصفات ما يمكن صنعه من اكتشافات العالم الحالي.","game":"اللعبة","creators":"المبدعون","privacy":"الخصوصية","infinite_kicker":"ما وراء الدليل الأساسي","infinite_title":"اكتشافاتك لا تنتهي هنا","infinite_copy":"هذه اكتشافات بداية مشتركة وليست قائمة كاملة. ادمج ما تجده في اللعبة لإنشاء مواد وعناصر ونباتات ومخلوقات جديدة؛ فمساحة التركيبات الممكنة تستمر في النمو."},
    "ja": {"play":"無料でプレイ","language":"言語を選択","wiki":"Wiki","biomes":"バイオーム","materials":"素材","creatures":"生き物","plants":"植物","recipes":"レシピ","official":"公式ゲームガイド","overview":"Tiny Blockに存在するバイオーム、素材、レシピ、植物、生き物を探索しよう。","guide":"ガイド","catalog":"共通の初期発見を見て、その先は自分で作ろう。","world":"ワールド生成","biomes_intro":"浮島には明るい平原から氷河、浜辺、洞窟、火山地帯まで広がっています。","biome":"バイオーム","terrain":"地形","mining":"採掘と建築","materials_intro":"素材は出会うと流れ、落ち、凍り、燃え、変化します。","material":"素材","living":"生きた世界","creatures_intro":"光、水、洞窟、溶岩で異なる行動を見せる生き物に出会おう。","creature":"生き物","growing":"育つ発見","plants_intro":"花、つる、装飾植物、バイオーム固有の木を見つけよう。","plant":"植物","crafting":"クラフト","recipes_intro":"発見を組み合わせて道具、収納、建築ブロック、明かりを作ろう。","ingredients":"材料","result":"完成品","recipe_caption":"ゲーム内レシピカタログでは、現在のワールドの発見から作れるものを確認できます。","game":"ゲーム","creators":"クリエイター","privacy":"プライバシー","infinite_kicker":"基本カタログのその先へ","infinite_title":"発見はここで終わらない","infinite_copy":"ここにあるのは全員共通の初期発見で、完全な一覧ではありません。ゲームで見つけたものを組み合わせ、新しい素材、アイテム、植物、生き物を作れます。可能な組み合わせは増え続けます。"},
    "ko": {"play":"무료 플레이","language":"언어 선택","wiki":"위키","biomes":"생물군계","materials":"재료","creatures":"생물","plants":"식물","recipes":"제작법","official":"공식 게임 가이드","overview":"Tiny Block의 생물군계, 재료, 제작법, 식물과 생물을 살펴보세요.","guide":"가이드","catalog":"공통 시작 발견을 살펴보고 나만의 발견을 만드세요.","world":"세계 생성","biomes_intro":"떠다니는 섬에는 밝은 평원부터 빙하, 해변, 동굴과 화산 지대까지 펼쳐집니다.","biome":"생물군계","terrain":"지형","mining":"채굴과 건설","materials_intro":"재료는 만나면 흐르고, 떨어지고, 얼고, 타며 새로운 것으로 변합니다.","material":"재료","living":"살아 있는 세계","creatures_intro":"빛, 물, 동굴과 용암에서 다르게 행동하는 생물을 만나보세요.","creature":"생물","growing":"자라는 발견","plants_intro":"꽃, 덩굴, 장식 식물과 생물군계별 나무를 발견하세요.","plant":"식물","crafting":"제작","recipes_intro":"발견물을 조합해 도구, 보관함, 건축 블록과 조명을 만드세요.","ingredients":"재료","result":"결과","recipe_caption":"게임 내 제작법 도감에서 현재 세계의 발견물로 만들 수 있는 것을 확인할 수 있습니다.","game":"게임","creators":"크리에이터","privacy":"개인정보","infinite_kicker":"기본 도감 너머","infinite_title":"발견은 여기서 끝나지 않습니다","infinite_copy":"여기에 나온 것은 모두가 공유하는 시작 발견이며 전체 목록이 아닙니다. 게임에서 찾은 것을 조합해 새로운 재료, 아이템, 식물과 생물을 만들 수 있으며 가능한 조합은 계속 늘어납니다."},
    "ru": {"play":"Играть бесплатно","language":"Выбрать язык","wiki":"Вики","biomes":"Биомы","materials":"Материалы","creatures":"Существа","plants":"Растения","recipes":"Рецепты","official":"Официальный гид по игре","overview":"Изучи биомы, материалы, рецепты, растения и существа, уже живущие в Tiny Block.","guide":"Гид","catalog":"Изучи общие стартовые открытия — а затем создавай свои.","world":"Генерация мира","biomes_intro":"Парящие острова ведут от светлых равнин к ледникам, пляжам, пещерам и вулканическим землям.","biome":"Биом","terrain":"Ландшафт","mining":"Добыча и строительство","materials_intro":"Материалы текут, падают, замерзают, горят и превращаются при взаимодействии.","material":"Материал","living":"Живые миры","creatures_intro":"Познакомься с существами, которые по-разному ведут себя на свету, в воде, пещерах и лаве.","creature":"Существо","growing":"Живые открытия","plants_intro":"Открой цветы, лианы, декоративные растения и деревья разных биомов.","plant":"Растение","crafting":"Крафт","recipes_intro":"Соединяй открытия и создавай инструменты, хранилища, строительные блоки и освещение.","ingredients":"Ингредиенты","result":"Результат","recipe_caption":"В игровом каталоге рецептов показано, что можно создать из открытий текущего мира.","game":"Игра","creators":"Авторам","privacy":"Конфиденциальность","infinite_kicker":"За пределами базового каталога","infinite_title":"Открытия здесь не заканчиваются","infinite_copy":"Здесь показаны общие стартовые открытия, а не полный список. Соединяй найденное в игре и создавай новые материалы, предметы, растения и существа — пространство возможных комбинаций продолжает расти."},
    "zh-hans": {"play":"免费游玩","language":"选择语言","wiki":"百科","biomes":"生物群系","materials":"材料","creatures":"生物","plants":"植物","recipes":"合成配方","official":"官方游戏指南","overview":"探索Tiny Block中的生物群系、材料、配方、植物和生物。","guide":"指南","catalog":"查看共享的初始发现，然后创造属于你的发现。","world":"世界生成","biomes_intro":"浮空岛从明亮平原延伸至冰川、海滩、洞穴与火山地带。","biome":"生物群系","terrain":"地形","mining":"采掘与建造","materials_intro":"材料相遇时会流动、坠落、冻结、燃烧并发生转化。","material":"材料","living":"鲜活世界","creatures_intro":"认识在阳光、水域、洞穴与熔岩中表现各异的生物。","creature":"生物","growing":"生长发现","plants_intro":"发现花朵、藤蔓、装饰植物与各生物群系的树木。","plant":"植物","crafting":"合成","recipes_intro":"组合发现，解锁工具、储物、建筑方块与照明。","ingredients":"材料","result":"结果","recipe_caption":"游戏内配方图鉴会显示当前世界中的发现可以合成什么。","game":"游戏","creators":"创作者","privacy":"隐私政策","infinite_kicker":"超越基础图鉴","infinite_title":"你的发现不会止步于此","infinite_copy":"这里展示的是所有玩家共享的初始发现，并非完整列表。在游戏中组合你找到的内容，创造新材料、物品、植物与生物；可能的组合空间会不断增长。"},
    "zh-hant": {"play":"免費遊玩","language":"選擇語言","wiki":"百科","biomes":"生態域","materials":"材料","creatures":"生物","plants":"植物","recipes":"合成配方","official":"官方遊戲指南","overview":"探索Tiny Block中的生態域、材料、配方、植物和生物。","guide":"指南","catalog":"查看共享的初始發現，然後創造屬於你的發現。","world":"世界生成","biomes_intro":"浮空島從明亮平原延伸至冰川、海灘、洞穴與火山地帶。","biome":"生態域","terrain":"地形","mining":"採掘與建造","materials_intro":"材料相遇時會流動、墜落、凍結、燃燒並發生轉化。","material":"材料","living":"鮮活世界","creatures_intro":"認識在陽光、水域、洞穴與熔岩中表現各異的生物。","creature":"生物","growing":"生長發現","plants_intro":"發現花朵、藤蔓、裝飾植物與各生態域的樹木。","plant":"植物","crafting":"合成","recipes_intro":"組合發現，解鎖工具、儲物、建築方塊與照明。","ingredients":"材料","result":"結果","recipe_caption":"遊戲內配方圖鑑會顯示目前世界中的發現可以合成什麼。","game":"遊戲","creators":"創作者","privacy":"隱私權政策","infinite_kicker":"超越基礎圖鑑","infinite_title":"你的發現不會止步於此","infinite_copy":"這裡展示的是所有玩家共享的初始發現，並非完整清單。在遊戲中組合你找到的內容，創造新材料、物品、植物與生物；可能的組合空間會持續成長。"},
}

BIOME_VARIETY = {
    "en": {"kicker":"Every world is different","title":"Biomes form new landscapes","copy":"These are the core environments, not fixed maps. Each seed rearranges terrain, caves, water, structures, plants, and creatures into a different world."},
    "de": {"kicker":"Jede Welt ist anders","title":"Biome formen neue Landschaften","copy":"Dies sind die grundlegenden Umgebungen, keine festen Karten. Jeder Seed ordnet Gelände, Höhlen, Wasser, Bauwerke, Pflanzen und Kreaturen zu einer anderen Welt an."},
    "es": {"kicker":"Cada mundo es diferente","title":"Los biomas forman nuevos paisajes","copy":"Estos son los entornos básicos, no mapas fijos. Cada semilla reorganiza terreno, cuevas, agua, estructuras, plantas y criaturas para crear un mundo diferente."},
    "fr": {"kicker":"Chaque monde est différent","title":"Les biomes créent de nouveaux paysages","copy":"Ce sont les environnements de base, pas des cartes figées. Chaque graine réorganise terrain, grottes, eau, structures, plantes et créatures pour former un monde différent."},
    "it": {"kicker":"Ogni mondo è diverso","title":"I biomi formano nuovi paesaggi","copy":"Questi sono gli ambienti di base, non mappe fisse. Ogni seed dispone terreno, grotte, acqua, strutture, piante e creature in un mondo diverso."},
    "pt-br": {"kicker":"Cada mundo é diferente","title":"Biomas formam novas paisagens","copy":"Estes são os ambientes básicos, não mapas fixos. Cada semente reorganiza terreno, cavernas, água, estruturas, plantas e criaturas em um mundo diferente."},
    "ar": {"kicker":"كل عالم مختلف","title":"المناطق الحيوية تصنع مناظر جديدة","copy":"هذه بيئات أساسية وليست خرائط ثابتة. تعيد كل بذرة ترتيب التضاريس والكهوف والماء والمنشآت والنباتات والمخلوقات لتشكّل عالمًا مختلفًا."},
    "ja": {"kicker":"ワールドごとに違う","title":"バイオームが新しい景色を作る","copy":"ここにあるのは基本環境であり、固定マップではありません。シードごとに地形、洞窟、水、建造物、植物、生き物の配置が変わり、異なる世界が生まれます。"},
    "ko": {"kicker":"세계마다 다릅니다","title":"생물군계가 새로운 풍경을 만듭니다","copy":"여기에 나온 것은 기본 환경이며 고정된 지도가 아닙니다. 시드마다 지형, 동굴, 물, 구조물, 식물과 생물의 배치가 달라져 새로운 세계가 만들어집니다."},
    "ru": {"kicker":"Каждый мир уникален","title":"Биомы складываются в новые ландшафты","copy":"Это базовые природные зоны, а не готовые карты. Каждый сид по-новому соединяет рельеф, пещеры, воду, постройки, растения и существ — так появляются разные миры."},
    "zh-hans": {"kicker":"每个世界都不同","title":"生物群系组合成全新景观","copy":"这些是基础环境，并非固定地图。每个种子都会重新排列地形、洞穴、水域、结构、植物与生物，形成不同的世界。"},
    "zh-hant": {"kicker":"每個世界都不同","title":"生態域組合成全新景觀","copy":"這些是基礎環境，並非固定地圖。每個種子都會重新排列地形、洞穴、水域、建築、植物與生物，形成不同的世界。"},
}

TERMS = {
    "en": ["Plains","Forest","Tundra","Ice Fields","Desert","Obsidian Wastes","Beach","Riverbank","Cavern","Volcanic","Oak","Palm","Pine","Meadow Bloom","Prairie Sprig","Cave Vines","Weeping Tree","Packed Ice","Lantern","Stone Bricks","Sandstone","Watcher Bloom","Cave Spider"],
    "de": ["Ebenen","Wald","Tundra","Eisfelder","Wüste","Obsidian-Ödland","Strand","Flussufer","Höhle","Vulkanland","Eiche","Palme","Kiefer","Wiesenblüte","Präriespross","Höhlenranken","Trauerbaum","Packeis","Laterne","Steinziegel","Sandstein","Wächterblüte","Höhlenspinne"],
    "es": ["Llanuras","Bosque","Tundra","Campos de hielo","Desierto","Páramos de obsidiana","Playa","Ribera","Caverna","Volcánico","Roble","Palmera","Pino","Flor de pradera","Brote de pradera","Enredaderas de cueva","Árbol llorón","Hielo compacto","Farol","Ladrillos de piedra","Arenisca","Flor vigilante","Araña de cueva"],
    "fr": ["Plaines","Forêt","Toundra","Champs de glace","Désert","Terres d’obsidienne","Plage","Rive","Caverne","Volcanique","Chêne","Palmier","Pin","Fleur des prés","Brin de prairie","Lianes cavernicoles","Arbre pleureur","Glace compactée","Lanterne","Briques de pierre","Grès","Fleur guetteuse","Araignée des cavernes"],
    "it": ["Pianure","Foresta","Tundra","Campi di ghiaccio","Deserto","Distese d’ossidiana","Spiaggia","Riva del fiume","Caverna","Vulcanico","Quercia","Palma","Pino","Fiore di prato","Germoglio di prateria","Liane di grotta","Albero piangente","Ghiaccio compatto","Lanterna","Mattoni di pietra","Arenaria","Fiore sentinella","Ragno delle caverne"],
    "pt-br": ["Planícies","Floresta","Tundra","Campos de gelo","Deserto","Ermos de obsidiana","Praia","Margem do rio","Caverna","Vulcânico","Carvalho","Palmeira","Pinheiro","Flor do campo","Ramo da pradaria","Trepadeiras da caverna","Árvore-chorona","Gelo compactado","Lanterna","Tijolos de pedra","Arenito","Flor sentinela","Aranha da caverna"],
    "ar": ["السهول","الغابة","التندرا","حقول الجليد","الصحراء","أراضي السبج","الشاطئ","ضفة النهر","الكهف","بركاني","بلوط","نخلة","صنوبر","زهرة المرج","غصن البراري","كروم الكهف","الشجرة الباكية","جليد مضغوط","فانوس","طوب حجري","حجر رملي","زهرة المراقب","عنكبوت الكهف"],
    "ja": ["平原","森","ツンドラ","氷原","砂漠","黒曜石の荒地","浜辺","川岸","洞窟","火山地帯","オーク","ヤシ","マツ","草原の花","プレーリーの芽","洞窟のつる","しだれ木","氷塊","ランタン","石レンガ","砂岩","見張り花","洞窟グモ"],
    "ko": ["평원","숲","툰드라","빙원","사막","흑요석 황무지","해변","강둑","동굴","화산 지대","참나무","야자나무","소나무","초원꽃","대초원 새싹","동굴 덩굴","수양나무","단단한 얼음","랜턴","돌 벽돌","사암","감시꽃","동굴 거미"],
    "ru": ["Равнины","Лес","Тундра","Ледяные поля","Пустыня","Обсидиановые пустоши","Пляж","Берег реки","Пещера","Вулканический","Дуб","Пальма","Сосна","Луговой цветок","Степной росток","Пещерные лианы","Плакучее дерево","Плотный лёд","Фонарь","Каменные кирпичи","Песчаник","Цветок-наблюдатель","Пещерный паук"],
    "zh-hans": ["平原","森林","苔原","冰原","沙漠","黑曜石荒地","海滩","河岸","洞穴","火山地带","橡树","棕榈树","松树","草甸花","草原嫩枝","洞穴藤蔓","垂枝树","浮冰","灯笼","石砖","砂岩","守望花","洞穴蜘蛛"],
    "zh-hant": ["平原","森林","苔原","冰原","沙漠","黑曜石荒地","海灘","河岸","洞穴","火山地帶","橡樹","棕櫚樹","松樹","草甸花","草原嫩枝","洞穴藤蔓","垂枝樹","浮冰","燈籠","石磚","砂岩","守望花","洞穴蜘蛛"],
}

TERM_KEYS = ["plains","forest","tundra","ice-fields","desert","obsidian","beach","riverbank","cavern","volcanic","oak","palm","pine","meadow-bloom","prairie-sprig","cave-vines","weeping-tree","packed-ice","lantern","stone-bricks","sandstone","watcher-bloom","cave-spider"]

TERMS = {code: dict(zip(TERM_KEYS, values, strict=True)) for code, values in TERMS.items()}
